platform :ios, '9.0'

def shared_pods
  # REACT NATIVE
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  ## In Xcode: Pods project -> select React Target -> Build Settings -> set Require Only App-Extension-Safe API to No 
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'RCTActionSheet',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTPushNotification',
    'DevSupport',
  ]

  # THIRD PARTY
  ## In Xcode: Pods project -> select React Target -> Build Settings -> set Require Only App-Extension-Safe API to No 
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  
  # REACT NATIVE FIREBASE
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios/RNFirebase.podspec'
  
  # FIREBASE MODULES
  pod 'Firebase/Core', '~> 5.3.0'
end

# APP ONLY
target 'react-native-starter' do
  shared_pods
  
  # THIRD PARTY
  pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'
end

# EXTENSION ONLY
target 'ShareExtension' do
  shared_pods

  # THIRD PARTY
  pod 'react-native-share-extension', :path => '../node_modules/react-native-share-extension'
end
